name: readmore_flutter
example: example/lib/main.dart

description: "A Flutter package that provides a customizable 'Read More'/'Show Less' text widget with flexible truncation options."
repository: https://github.com/mohammadaminiaf/read_more
homepage: https://github.com/mohammadaminiaf/read_more
version: 1.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add this line to ensure the library file is included
  # assets:
  #   - lib/read_more_flutter.dart
